---
title: "esa_analysis_check"
author: "Bryan Milstead"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(stringsAsFactors = FALSE) 
library(knitr)
library(vegan)
#library(vegan3d)
library(ecodist)
library(readxl)
library(ggplot2)
library(randomForest)
#library(labdsv) #this messes with the tidyverse; call explicitly in the indicator species analysis
library(tidyverse)
library(here)
library(wesanderson)
library(hrbrthemes)  #+ theme_ipsum()
library(viridis)
```


```{r data, include=FALSE, echo=FALSE, eval=FALSE} 

#get the 2007 count data.  Data source: 'https://www.epa.gov/sites/production/files/2014-10/nla2007_phytoplankton_softalgaecount_20091023.csv'
counts<-read.csv(here("data/nla2007_phytoplankton_softalgaecount_20091023.csv"),na.strings=c("NA",""," "))
    nrow(counts) #31971
    
counts<-filter(counts,VISIT_NO==1,LAKE_SAMP=='Target_Sampled',!is.na(GENUS))
  nrow(counts) #26394

counts<-filter(counts,GENUS!=('Undetermined'),GENUS!=('(Undetermined)'),GENUS!="Dinobryon (empty lorica)",GENUS!="Encapsulating Chrysophyte")
  nrow(counts) #26382

t2007 <- group_by(counts,SITE_ID,TAXONOMIST_CNT,GENUS)%>%
  summarise(abund=sum(ABUND, na.rm = TRUE))
    names(t2007)<-tolower(names(t2007))
        nrow(t2007) #24151
t2007<-ungroup(t2007)

#create phyto07  all phytoplankton
phyto07<-spread(t2007,genus,abund) #1148  260
phyto07[is.na(phyto07)] <- 0 
    #save the taxonomist_cnt data to add to env below
      taxonomist_chk<-select(phyto07,site_id,taxonomist=taxonomist_cnt)%>%mutate(taxonomist=ifelse(taxonomist=="Dawn Perkins","DP",taxonomist))
    #remove taxonomist_cnt
      
phyto07_chk<-select(phyto07,-taxonomist_cnt) #1,148 × 259
save(phyto07_chk,taxonomist_chk,file=here('data/phyto07_chk.rda'))

```

```{r data1, include=FALSE, echo=FALSE, cache=FALSE} 
load(file=here('data/phyto07_chk.rda'))

```

* run the NMDS on the phyto abundances 
```{r NMS07, include=FALSE, echo=FALSE, cache=FALSE,eval=FALSE} 
nms07_chk<-metaMDS(phyto07_chk[,-1],k=4,trymax=1000,parallel=32)
save(nms07_chk,file=here("data/nms07_chk.rda"))
```

```{r loadNMS07, include=FALSE,eval=TRUE}
load(here("data/nms07_chk.rda"))
```

* Plot the first two NMDS score

```{r plotNMDS, include=FALSE}
#sites from NMS
sites <- as.data.frame(scores(nms07_chk, display = "sites"))

#add taxonomist
sites<-cbind(sites,select(taxonomist_chk,taxonomist))

qq<-ggplot(sites,aes(x=NMDS1,y=NMDS2)) + geom_point(colour="#31688EFF",size=3) + ggtitle("Rerun of Plot of NMDS Scores")+
  theme(plot.title = element_text(lineheight=4.8, face="bold",hjust = 0.5))
                               
qq 

###output plot
jpeg(here("output/nms_chk_scores.jpeg")) 
qq
dev.off()

```

* Plot the first two NMDS score colored by taxonomist

```{r plotNMDS, include=FALSE}
n<-6  #number of colors
#type<-"discrete"
type<-"continuous"

#pal<-c(2:7)
pal<-viridis_pal()(n)
#pal<-wes_palette("Zissou", n, type =type)
#pal<-wes_palette("FantasticFox", n, type =type)
#pal<-wes_palette("Darjeeling", n, type =type)

qq<-ggplot(sites,aes(x=NMDS1,y=NMDS2)) + geom_point(aes(x=NMDS1,y=NMDS2,col=factor(taxonomist)),size=3) + ggtitle("Rerun of NMDS Scores Colored by Taxonomist ")+
  scale_color_manual(values=pal,                          #c("red", "blue","orange"), 
                  name="Taxonomist",
                  breaks=c('DP', 'EEW', 'JKE',  'JS', 'KMM',  'MH' ),
                  labels=c('DP', 'EEW', 'JKE',  'JS', 'KMM',  'MH' ))+
  theme(plot.title = element_text(lineheight=4.8, face="bold",hjust = 0.5))


                               
qq 

###output plot
jpeg(here("output/chk_nms_grp_taxonomist.jpeg")) 
qq
dev.off()

```

